version: '3'

volumes:
  openldap_database:
    driver: local
    driver_opts:
      type: none
      device: ${OPENLDAP_DATABASE_DIR:-/tmp/openldap_database}
      o: bind
  openldap_config:
    driver: local
    driver_opts:
      type: none
      device: ${OPENLDAP_CONFIG_DIR:-/tmp/openldap_config}
      o: bind
  openldap_certs:
    driver: local
    driver_opts:
      type: none
      device: ${OPENLDAP_CERTS_DIR:-/tmp/openldap_certs}
      o: bind
