version: '3'

services:
  openldap:
    environment:
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    volumes:
      - openldap_cert:/container/service/slapd/assets/certs
    ports:
      - "${OPENLDAP_SSL_PORT:-636}:636"

volumes:
  openldap_cert:
